site_name: TejithasSilkPetals
site_dir: site
docs_dir: docs/
theme:
  name: material

  palette:
    scheme: default #slate #> dark mode
    primary: indigo
    accent: blue

  features:
      # Makes the main navigation items appear as a top bar for a cleaner look
      - navigation.tabs
      # Keeps the table of contents visible while scrolling
      - toc.follow
      # Enables the "Back to top" button
      - content.action.top
      # Adds a copy button to code blocks (great motivation for users to try code!)
      - content.code.copy
      # Shows the hierarchy of the current page in the header
      - navigation.path
      # Expands all navigation sections by default
      #- navigation.expand

  font:
    text: Roboto
    code: Roboto Mono


markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
extra_css:
  - css/extra.css
plugins:
  - search

nav:
  - Home: README.md

  - EthnicWear:
    - Main: EthnicWear/EthnicWear-Main.md

  - Jewellery:
    - Main: Jewellery/Jewelry-Main.md
    - Catlogue: Jewellery/Jewelery-Catlogue.md

  - Decor:
    - Main: Decor/Decor-main.md



